spring:
      datasource:
        url: jdbc:mariadb://localhost:3306/incidents
        driver-class-name: org.mariadb.jdbc.Driver
        database: incidents
        password: 3num@ Elish
        username: root
      jpa:
        show-sql: false
        hibernate:
          ddl-auto: update
          use-new-id-generator-mappings: false
        database: mysql